load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "linked_list",
    hdrs = [
        "include/algorithms/linked_list.hpp",
        "include/algorithms/linked_list.tpp",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"]
)
